INSERT INTO CATEGORY (DESCRIPTION) VALUES ('America');
INSERT INTO CATEGORY (DESCRIPTION) VALUES ('Vegetarian');
INSERT INTO CATEGORY (DESCRIPTION) VALUES ('Fast Food');
INSERT INTO CATEGORY (DESCRIPTION) VALUES ('Vegan');
INSERT INTO UNIT_OF_MEASURE (UOM) VALUES ('Teaspoon');
INSERT INTO UNIT_OF_MEASURE (UOM) VALUES ('TableSpoon');
INSERT INTO UNIT_OF_MEASURE (UOM) VALUES ('Cup');
INSERT INTO UNIT_OF_MEASURE (UOM) VALUES ('Pinch');
INSERT INTO UNIT_OF_MEASURE (UOM) VALUES ('Ounce');